# Generated by Django 5.2.1 on 2026-04-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_outboxevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboxevent',
            name='max_retries',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='outboxevent',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='outboxevent',
            name='exchange',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='outboxevent',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='outboxevent',
            name='last_error',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='outboxevent',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='outboxevent',
            name='routing_key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='outboxevent',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('dead_lettered', 'Dead Lettered')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='outboxevent',
            index=models.Index(fields=['status', 'next_retry_at'], name='todos_outbo_status_da77c1_idx'),
        ),
        migrations.AddIndex(
            model_name='outboxevent',
            index=models.Index(fields=['status', 'created_at'], name='todos_outbo_status_b1b4a9_idx'),
        ),
    ]
